#!/usr/bin/env python
"""Generate the CLI command reference under `doc/cli/reference/` from the real argparse tree.

Run it with `bin/gen-cli-reference` (or `bin/gen-docs`, which also builds the documentation site).
The output is committed, but treated as a **build artifact rather than source**: it can be deleted
and rebuilt from the parser at any time, and nothing in CI checks that `main`'s copy is current.
It's committed only because Python projects have no build step -- an uncommitted file simply
wouldn't exist for anyone browsing GitHub, and the README links people straight at these pages.

So on `main` this is a cached copy that may lag behind the parser, refreshed whenever a developer
feels like running the command. `bin/cut-rc` regenerates it into every release commit, which is
where being current actually matters: a *published* version's README links at these pages, and
trusting whoever last pushed to have remembered is exactly the assumption that fails.

Why introspect the parser rather than scrape `cg --help`: the tree is already a real object
(`CliBase.init_parser()` builds it), so subcommands, options and help text come out structured
instead of being recovered from column-aligned text that changes shape with terminal width.

Output is deliberately boring--one page per command group, each command rendered as its own
`--help` output in a fenced block. That is the one form of CLI reference that cannot drift from the
tool, and `cg`'s help text is written well enough to carry it (see `cg status`, which explains why
it has no cached mode). Prose that explains *when* to reach for a command belongs in the
hand-written guides under `doc/cli/`, not here.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import posixpath
import sys
from collections.abc import Callable
from pathlib import Path

LinkFor = Callable[[tuple[str, ...]], "str | None"]
"""Resolves a command path to a link from the page currently being rendered, or None if that command
   has no rendered heading to point at."""

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from codingame_tools.cli.main import CgCli  # noqa: E402  (needs the path fix above)

HELP_WIDTH = 100
"""Fixed formatting width. argparse otherwise wraps to `COLUMNS`/the terminal, so without this the
   generated files would depend on the size of whatever window they happened to be generated in."""

GENERATED_HEADER = "<!-- Generated by scripts/gen_cli_docs.py. Do not edit; run `bin/gen-cli-reference`. -->"

REFERENCE_SUBDIR = Path("doc") / "cli" / "reference"

# Command groups that get a page to themselves. Anything not listed (and not under `api`) lands on
# the top-level page. `api` is special-cased: it has 22 service endpoints, so each gets its own page.
GROUP_TITLES = {
    "puzzle": "cg puzzle",
    "contribution": "cg contribution",
    "settings": "cg settings",
    "config": "cg config",
    "docker": "cg docker",
    "raw-api": "cg raw-api",
    "api-helper": "cg api-helper",
}

TOP_LEVEL_PAGE = "top-level"
API_SUBDIR = "api"


class CommandNode:
    """One node of the parser tree: a command path plus the parser that implements it."""

    def __init__(self, path: tuple[str, ...], parser: argparse.ArgumentParser, summary: str) -> None:
        self.path = path
        self.parser = parser
        self.summary = summary

    @property
    def invocation(self) -> str:
        return " ".join(("cg", *self.path))

    @property
    def short_summary(self) -> str:
        """First sentence of the summary, for the page's index table.

           argparse hands back the command's entire description here, which is a paragraph for most
           of `cg`'s commands--fine inside the fenced help block below, unreadable as a table cell."""
        text = self.summary
        for end in (". ", "--"):
            head, sep, _ = text.partition(end)
            if sep and len(head) >= 40:
                text = head + ("." if end == ". " else "")
                break
        return text if len(text) <= 160 else text[:157].rstrip() + "..."

    @property
    def anchor(self) -> str:
        return "cg-" + "-".join(self.path) if self.path else "cg"

    def help_text(self) -> str:
        return self.parser.format_help().rstrip()


def _summaries(parser: argparse.ArgumentParser) -> dict[str, str]:
    """One-line summaries for `parser`'s subcommands, as shown in its own help listing."""
    result: dict[str, str] = {}
    for action in parser._actions:  # noqa: SLF001  (argparse exposes no public traversal API)
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            for choice in action._get_subactions():  # noqa: SLF001
                result[choice.dest] = " ".join((choice.help or "").split())
    return result


def walk(parser: argparse.ArgumentParser, path: tuple[str, ...] = (), summary: str = "") -> list[CommandNode]:
    """Every command in the tree rooted at `parser`, depth-first in declaration order."""
    nodes = [CommandNode(path, parser, summary)]
    summaries = _summaries(parser)
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            for name, sub in action.choices.items():
                nodes += walk(sub, (*path, name), summaries.get(name, ""))
    return nodes


def page_for(node: CommandNode) -> str:
    """Which generated page a command belongs on, as a path relative to `REFERENCE_SUBDIR`."""
    if not node.path:
        return TOP_LEVEL_PAGE
    head = node.path[0]
    if head == "api":
        # `cg api` itself indexes the services; each service endpoint gets its own page.
        return f"{API_SUBDIR}/index" if len(node.path) == 1 else f"{API_SUBDIR}/{node.path[1]}"
    if head in GROUP_TITLES:
        return head
    return TOP_LEVEL_PAGE



def _link_to(from_page: str, to_page: str, anchor: str) -> str:
    """A link from one generated page to a command's heading on another (or the same) page.

       Pages sit at varying depths under `doc/cli/reference/` (`docker.md`, but `api/vote.md`), so
       the path is computed rather than assumed--otherwise every link out of an `api/` page would be
       off by one directory."""
    if from_page == to_page:
        return f"#{anchor}"
    from_dir = posixpath.dirname(from_page) or "."
    return f"{posixpath.relpath(to_page + '.md', from_dir)}#{anchor}"


def _metavar_for(action: argparse.Action) -> str:
    """What a value for `action` is called, with `nargs` reflected in the brackets.

       argparse builds this internally but exposes no way to ask for it, so it is rebuilt here
       rather than scraped back out of `format_help()`'s wrapped, column-aligned text."""
    if action.metavar:
        name = action.metavar if isinstance(action.metavar, str) else " ".join(action.metavar)
    elif action.choices:
        name = "{" + ",".join(str(c) for c in action.choices) + "}"
    else:
        name = action.dest.upper()
    nargs = action.nargs
    if nargs == 0:
        return ""
    if nargs == "?":
        return f"[{name}]"
    if nargs == "*":
        return f"[{name} ...]"
    if nargs == "+":
        return f"{name} [{name} ...]"
    if isinstance(nargs, int):
        return " ".join([name] * nargs)
    return name


def _invocation(action: argparse.Action) -> str:
    """How the user types `action`: `PATH`, or `-l, --languages LANGUAGE [LANGUAGE ...]`."""
    metavar = _metavar_for(action)
    if not action.option_strings:            # a positional
        return metavar or action.dest
    # Short forms first (`-l, --languages`), regardless of declaration order: a reader scanning for
    # a flag wants the terse spelling adjacent to the name it explains.
    spellings = ", ".join(sorted(action.option_strings, key=lambda o: (not o.startswith("--"), o))[::-1])
    return f"{spellings} {metavar}".rstrip()


def _suffixes(action: argparse.Action) -> str:
    """Trailing notes that argparse's own help never states: defaults, and whether a value is
       optional. Choices are already visible in the metavar."""
    notes: list[str] = []
    default = action.default
    if (default not in (None, False, argparse.SUPPRESS)
            and not isinstance(action, argparse._SubParsersAction)):  # noqa: SLF001
        notes.append(f"default: `{default}`")
    if action.option_strings and action.required:
        notes.append("required")
    return f" *({'; '.join(notes)})*" if notes else ""


def _render_actions(title: str, actions: list[argparse.Action]) -> list[str]:
    """One bullet per argument. A list rather than a table because the longest help string here is
       424 characters and multi-sentence--unreadable in a cell, fine in a bullet that reflows."""
    if not actions:
        return []
    lines = [f"**{title}**", ""]
    for action in actions:
        help_text = " ".join((action.help or "").split())
        lines.append(f"- **`{_invocation(action)}`**{_suffixes(action)}"
                     + (f" — {help_text}" if help_text else ""))
    lines.append("")
    return lines


def _render_command(node: CommandNode, link_for: LinkFor) -> list[str]:
    """One command: description, usage, then its arguments, options and subcommands."""
    parser = node.parser
    lines = [f"## `{node.invocation}`", ""]

    description = " ".join((parser.description or "").split())
    if description:
        lines += [description, ""]

    # The usage line stays fenced: it is the one part that is genuinely preformatted, and argparse
    # already wraps it to HELP_WIDTH deterministically.
    lines += ["```text", parser.format_usage().rstrip(), "```", ""]

    positionals: list[argparse.Action] = []
    optionals: list[argparse.Action] = []
    subcommands: list[argparse.Action] = []
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            subcommands.append(action)
        elif isinstance(action, argparse._HelpAction):  # noqa: SLF001
            # Every command has it and it does the obvious thing. Listed first under every single
            # Options heading it is pure noise, so the page says it once instead.
            continue
        elif action.option_strings:
            optionals.append(action)
        else:
            positionals.append(action)

    lines += _render_actions("Arguments", positionals)
    lines += _render_actions("Options", optionals)

    for action in subcommands:
        summaries = {c.dest: " ".join((c.help or "").split()) for c in action._get_subactions()}  # noqa: SLF001
        if not summaries:
            continue
        lines += ["**Subcommands**", ""]
        for name, summary in summaries.items():
            # Linked wherever the target was actually rendered--which may be a different page, since
            # `cg api`'s endpoints each get one of their own. Plain text if it wasn't rendered at
            # all, so a link can never dangle.
            href = link_for((*node.path, name))
            label = f"[**`{name}`**]({href})" if href else f"**`{name}`**"
            lines.append("- " + label + (f" — {summary}" if summary else ""))
        lines.append("")
    return lines


def render_page(title: str, intro: str, nodes: list[CommandNode], depth: int,
                link_for: LinkFor = lambda _path: None) -> str:
    """One reference page: a heading, an intro, then every command as its own `--help` block."""
    up = "../" * depth
    lines = [
        GENERATED_HEADER,
        "",
        f"# {title}",
        "",
        intro,
        "",
    ]
    lines += ["Every command also accepts `-h` / `--help`.", ""]
    if len(nodes) > 1:
        lines += ["| Command | Summary |", "| --- | --- |"]
        for node in nodes:
            summary = node.short_summary or "--"
            lines.append(f"| [`{node.invocation}`](#{node.anchor}) | {summary} |")
        lines.append("")
    for node in nodes:
        lines += _render_command(node, link_for)
    lines += [
        "---",
        "",
        f"Generated from the parser itself. For *when* to use these, see the "
        f"[CLI guides]({up}../index.md).",
        "",
    ]
    return "\n".join(lines)


def render_index(pages: dict[str, list[CommandNode]]) -> str:
    """The reference landing page: one row per generated page, with its command count."""
    lines = [
        GENERATED_HEADER,
        "",
        "# CLI command reference",
        "",
        "Every `cg` command, generated from the parser so it cannot drift from the tool. Start with"
        " the [CLI guides](../index.md) if you're looking for how to get something done rather than"
        " what a specific flag means.",
        "",
        "| Page | Commands |",
        "| --- | --- |",
    ]
    for name in sorted(pages):
        if name == f"{API_SUBDIR}/index":
            continue
        if name == TOP_LEVEL_PAGE:
            title = "Top-level commands"
        elif name.startswith(f"{API_SUBDIR}/"):
            title = f"`cg api {name.split('/', 1)[1]}`"
        else:
            title = f"`cg {name}`"
        lines.append(f"| [{title}]({name}.md) | {len(pages[name])} |")
    lines += ["", "---", ""]
    return "\n".join(lines)


def generate(output_root: Path) -> list[Path]:
    """Write the whole reference under `output_root/doc/cli/reference/`. Returns the files written."""
    # Both of these pin *terminal-dependent rendering*, which is the one way this generator can
    # produce different files from identical source. argparse decides each independently, from the
    # environment of whatever process happens to be running.
    os.environ["COLUMNS"] = str(HELP_WIDTH)
    # Python 3.14's argparse colourises help when `sys.stdout` is a terminal. That's right for a
    # human running `cg --help` and wrong here, where `format_help()` is captured into files:
    # generating from an interactive shell embedded raw ANSI escapes in every page, while a piped
    # run produced clean text. `PYTHON_COLORS` is argparse's own off-switch and is consulted before
    # `NO_COLOR`, `FORCE_COLOR` and the isatty check, so it holds regardless of the caller's
    # environment. See `_colorize.can_colorize`.
    os.environ["PYTHON_COLORS"] = "0"
    # argparse derives every parser's `prog` from `sys.argv[0]`, which here is this script--so
    # without this every generated usage line would read `gen_cli_docs.py ...`.
    original_argv0 = sys.argv[0]
    sys.argv[0] = "cg"
    try:
        cli = CgCli(["--help"])
        asyncio.run(cli.init_parser())
    finally:
        sys.argv[0] = original_argv0

    nodes = walk(cli.parser)
    pages: dict[str, list[CommandNode]] = {}
    for node in nodes:
        pages.setdefault(page_for(node), []).append(node)

    # Where every command ended up, so a subcommand list can link across pages.
    located = {node.path: (page_for(node), node.anchor) for node in nodes}

    reference_dir = output_root / REFERENCE_SUBDIR
    written: list[Path] = []
    for name, page_nodes in pages.items():
        path = reference_dir / f"{name}.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        depth = len(Path(name).parts) - 1
        if name == TOP_LEVEL_PAGE:
            title, intro = "Top-level commands", (
                "`cg` itself, plus the commands that don't belong to a group--logging in, checking"
                " who you are, and inspecting session state.")
        elif name == f"{API_SUBDIR}/index":
            title, intro = "cg api", (
                "Thin wrappers over CodinGame's own service endpoints, one subcommand per API"
                " method. These speak the protocol directly and do no bookkeeping; the puzzle and"
                " contribution managers are built on top of them.")
        elif name.startswith(f"{API_SUBDIR}/"):
            service = name.split("/", 1)[1]
            title, intro = f"cg api {service}", (
                f"The `{service}` service endpoint. See [`cg api`](index.md) for how these relate to"
                " the higher-level commands.")
        else:
            title = GROUP_TITLES.get(name, f"cg {name}")
            intro = f"Every `{title}` subcommand."
        def link_for(path_: tuple[str, ...], _page: str = name) -> str | None:
            target = located.get(path_)
            return None if target is None else _link_to(_page, target[0], target[1])

        path.write_text(
                render_page(title, intro, page_nodes, depth, link_for), encoding="utf-8")
        written.append(path)

    index_path = reference_dir / "index.md"
    index_path.write_text(render_index(pages), encoding="utf-8")
    written.append(index_path)

    _prune_orphans(reference_dir, written)
    return written


def _prune_orphans(reference_dir: Path, written: list[Path]) -> None:
    """Delete generated pages that this run didn't produce, then any directories left empty.

       Writing alone isn't enough: rename `cg api vote` or drop a command group and its page would
       otherwise sit in the tree forever, indexed by nothing, describing a command that no longer
       exists. That used to be caught by the staleness test comparing the committed *set* of files
       against a fresh one; that test is gone (the reference is a build artifact now, not source--
       see the module docstring), so pruning has to happen here instead, at the only point that
       knows what the current command tree actually is.

       Deliberately narrow: only `*.md` strictly under `reference_dir`, which is generated in its
       entirety. Nothing hand-written lives there, and this must never be able to reach anything
       that does."""
    kept = {path.resolve() for path in written}
    for existing in reference_dir.rglob("*.md"):
        if existing.resolve() not in kept:
            existing.unlink()
    # Deepest first, so a directory emptied by the loop above is itself removable.
    for directory in sorted((p for p in reference_dir.rglob("*") if p.is_dir()), reverse=True):
        if not any(directory.iterdir()):
            directory.rmdir()


def main() -> None:
    output_root = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else REPO_ROOT
    written = generate(output_root)
    print(f"wrote {len(written)} files under {output_root / REFERENCE_SUBDIR}")


if __name__ == "__main__":
    main()
