"""Generate the CLI command reference at docs build time, one page per command group.

Run by mkdocs-gen-files (see `gen-files` in mkdocs.yml), the same way the API reference is produced
by scripts/gen_api_pages.py. Nothing is written into the working tree: the pages exist only inside
the build, so there is no committed copy that can drift from the argparse tree it describes.

That drift was the reason for the change. The reference used to be committed and regenerated by
hand, with nothing in CI checking it was current -- so a changed help string could ship a site
documenting the previous one. Generating during the build makes staleness unrepresentable rather
than merely discouraged.
"""

from __future__ import annotations

import sys
from pathlib import Path

import mkdocs_gen_files

SCRIPTS = Path(__file__).resolve().parent
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from gen_cli_docs import iter_pages  # noqa: E402  (needs the path fix above)

REFERENCE_ROOT = Path("cli") / "reference"
"""Where the pages land in the docs tree -- matching the nav entry in mkdocs.yml, and the URLs the
   README and doc/cli/index.md already link to."""

for page, content in iter_pages():
    with mkdocs_gen_files.open(REFERENCE_ROOT / page, "w") as fd:
        fd.write(content)
    # Point "edit this page" at the generator rather than at a file that does not exist.
    mkdocs_gen_files.set_edit_path(REFERENCE_ROOT / page, Path("..") / "scripts" / "gen_cli_docs.py")
