"""Command-line entry point.

```
python -m codingame_tools.puzzle_manager.debug TARGET_FILE TEST_INDEX [--puzzle-dir DIR]
```


VS Code debugger launcher for a puzzle working directory's solution--a thin, puzzle_manager-aware
wrapper around `codingame_tools.test_runner.debug_stdin.run_debug_stdin`. TARGET_FILE (VS Code's
own `${file}` macro) is used only to *infer* the puzzle working directory (see
`codingame_tools.puzzle_manager.resolver.infer_puzzle_dir`) when `--puzzle-dir` isn't given--
TEST_INDEX then selects which downloaded `.meta/tests/` test case's input/output to run against
(see `codingame_tools.puzzle_manager.test_cases_dir.list_downloaded_test_cases`).

No `--update-expected` here (unlike `codingame_tools.contribution_manager.debug`)--`.meta/tests/`
is downloaded server truth, regenerated by `repair()`; there's nothing to accept a local run's
output as a new baseline for.

Not exported from `codingame_tools.puzzle_manager`'s own `__init__.py`--like `test_runner.
debug_stdin`, this is a `python -m` entry point, not a library import.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import cast

from ..client.client import CgClient
from ..test_runner import run_debug_stdin
from .manager import CgPuzzleManager
from .resolver import infer_puzzle_dir
from .test_cases_dir import list_downloaded_test_cases

__all__ = ["main"]


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
            prog="python -m codingame_tools.puzzle_manager.debug",
            description="Debug a puzzle solution under VS Code against a specific downloaded test case.",
        )
    parser.add_argument("target_file", type=Path, metavar="TARGET_FILE")
    parser.add_argument("test_index", type=int, metavar="TEST_INDEX")
    parser.add_argument(
            "--puzzle-dir", type=Path, default=None, metavar="DIR",
            help="Puzzle working directory. Defaults to inferring it from TARGET_FILE.",
        )
    args = parser.parse_args(argv)

    puzzle_dir = args.puzzle_dir if args.puzzle_dir is not None else infer_puzzle_dir(args.target_file)
    manager = CgPuzzleManager(puzzle_dir, cast(CgClient, None))
    matching = [tc for tc in list_downloaded_test_cases(manager.tests_dir) if tc.index == args.test_index]
    if not matching:
        raise SystemExit(f"No downloaded test case with index {args.test_index} under {manager.tests_dir}.")
    test_case = matching[0]

    # No `final_newline_added` here (unlike contribution_manager.debug): `.meta/tests/` holds
    # byte-exact fileservlet downloads, which are already the bytes CodinGame feeds stdin remotely.
    run_debug_stdin(test_case.input_file, args.target_file, test_case.output_file)


if __name__ == "__main__":
    main()
